
package lu.nowina.nexu.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FeedbackEndpoint", targetNamespace = "http://api.nexu.nowina.lu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FeedbackEndpoint {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "reportError", targetNamespace = "http://api.nexu.nowina.lu/", className = "lu.nowina.nexu.api.ReportError")
    @ResponseWrapper(localName = "reportErrorResponse", targetNamespace = "http://api.nexu.nowina.lu/", className = "lu.nowina.nexu.api.ReportErrorResponse")
    public void reportError(
        @WebParam(name = "arg0", targetNamespace = "")
        Feedback arg0);

}
